### ISSUE TITLE
Add permissions (Idea)

### ISSUE THREAD

**Issue by LowFr0nt** [Luziferium/Anti-Auto-Clicker#1]
It would be nice if you could use permissions to for example bypass the Anti Autoclicker. Hope this could be used in the future of this plugin.

**Comment by bsommerfeld** [comment]
Hi @LowFr0nt,

this is already integrated.

In the config.yml you can find a field named "BypassPermission", which represents the needed permissions to be bypassed from the plugin. You can also change that value to your needs.

Also make sure that the Bypass is enabled.
