### ISSUE TITLE
Compatibility problem with ItemsAdder!

### ISSUE THREAD

**Issue by ErythroCraft** [Luziferium/Anti-Auto-Clicker#2]
Hi

please fix the old version of org.apache.commons.io.FileUtils

ItemsAdder can not load!

**Comment by ErythroCraft** [comment]
Server:
 - CraftBukkit version 3262-Spigot-dc75aca-f0f801e (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

AntiAC v2.9.1-HOTFIX

**Comment by bsommerfeld** [comment]
Hey, what exactly happens? Any errors? Crashes?

**Comment by ErythroCraft** [comment]
Yes. Can not install ItemsAdder and other plugins, 
because **org.apache.commons.io.FilesUtils** is out of date.
```

package test;

import java.io.File;
import java.io.IOException;
import java.util.Collections;
import java.util.List;

import org.apache.commons.io.FileUtils;

public class ReadListOfLinesFromFileAndAlphabetize {

	public static void main(String[] args) {
		try {
			File file = new File("test.txt");
			List<String> lines = FileUtils.readLines(file);

			Collections.sort(lines);

			for (String line : lines) {
				System.out.println("line:" + line);
			}

		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}

```

**Comment by bsommerfeld** [comment]
If thats the issue, I will update it in the next update which comes soon :)
Thanks for reporting tho!
