### ISSUE TITLE
ShoutOutPunishment: false still sends message to discovered player

### ISSUE THREAD

**Issue by harvanchik** [Luziferium/Anti-Auto-Clicker#4]
Even with the setting `ShoutOutPunishment: false`, the message "You have been punished by the AutoClicker detection." is sent to the discovered player.

**Comment by bsommerfeld** [comment]
hi, yes, thats right. ShoutOutPunishment only includes the broadcast-message when someone got detected

**Comment by harvanchik** [comment]
So how do you prevent a discovered player from being sent that message? I don't want my players to know they've been discovered.

**Comment by bsommerfeld** [comment]
currently not possible, but i can add that to my bucketlist

**Comment by harvanchik** [comment]
Okay. I did find a temporary solution. I removed that line from the messages config file.
