### ISSUE TITLE
McMMO Not Compatible

### ISSUE THREAD

**Issue by Kowantify** [Luziferium/Anti-Auto-Clicker#5]
Currently McMMO has an ability for sword to enable "serated strike" which will have the player strike multiple mobs at once, like an overkill sweeping edge, come to find out this triggers Anti AC about every time, and I know this plugin hasn't been update in a while, so people found a way to get around it by setting their clicks about 10 seconds apart which I think is when Anti AC quits checking, I was wondering if there is a fix for these issues by chance I can implement or anything in that nature?

**Comment by bsommerfeld** [comment]
investigating

**Comment by bsommerfeld** [comment]
does this still occur with the latest version of antiac?

**Comment by bsommerfeld** [comment]
closed for now. should this reoccure please open another issue
