### ISSUE TITLE
When right-clicking and holding down

### ISSUE THREAD

**Issue by ghost** [Luziferium/Anti-Auto-Clicker#8]
There is a problem that auto-click detection detects when you right-click on a block for a long time. (They were just doing construction?)

**Comment by bsommerfeld** [comment]
hi, then your config is probably set too sensitive.

**Comment by fadfhkdfga** [comment]
I am using the default values generated by the plugin.

**Comment by ghost** [comment]
> hi, then your config is probably set too sensitive.

I am using the default values generated by the plugin.

**Comment by bsommerfeld** [comment]
with the default values this shouldn't happen. can you send me a video of what happens exactly while click checking?
